#!/usr/bin/env bash
#
# Copyright (c) 2026 Bryan C. Everly
# SPDX-License-Identifier: BSD-2-Clause
#
# Generate man/tmd.1 from the program's own --help output.
#
#   scripts/gen-man.sh BINARY OUTPUT        write the manpage
#   scripts/gen-man.sh --check BINARY PAGE  fail if the committed page is stale
#
# The option list, the exit statuses and the examples in the manpage are not
# maintained by hand: they are read out of `tmd --help`, which is itself
# generated from src/options.def. Adding an option therefore updates the help,
# the getopt table and the manpage together, and `make lint` runs the --check
# mode so a page that was not regenerated fails the build rather than quietly
# documenting an option that no longer exists.
#
# Only the prose sections below are written here. They are the part a generator
# cannot invent, and they are short enough to keep correct by reading them.
set -euo pipefail

CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
  shift
fi

BINARY="${1:?usage: gen-man.sh [--check] BINARY OUTPUT}"
OUTPUT="${2:?usage: gen-man.sh [--check] BINARY OUTPUT}"

[ -x "$BINARY" ] || { echo "gen-man.sh: $BINARY is not executable" >&2; exit 1; }

# The VERSION file, not the binary's --version: a working build reports
# "1.0.0.6-dev" (see scripts/version.sh), and the manpage is a committed file
# that must not change every time somebody edits a source file. The released
# number is what belongs in a manpage anyway.
VERSION="$(cat "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/VERSION")"
# The date is the manpage's own "last changed" field. It comes from the VERSION
# file's modification time rather than from `date`, so regenerating the page
# without changing anything does not produce a diff -- which is what makes the
# --check mode below meaningful.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATE="$(date -u -r "$REPO_ROOT/VERSION" '+%B %-d, %Y' 2>/dev/null || date -u '+%B %-d, %Y')"

# roff treats a leading '.' or '\' as markup and a hyphen as a soft one.
escape_roff() {
  sed -e 's/\\/\\\\/g' -e 's/^[.'"'"']/\\\&&/' -e 's/-/\\-/g'
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  cat <<HEADER
.\" Generated by scripts/gen-man.sh from \`tmd --help\` -- do not edit by hand.
.\" Run \`make man\` after changing src/options.def.
.\"
.\" Copyright (c) 2026 Bryan C. Everly
.\" SPDX-License-Identifier: BSD-2-Clause
.TH TMD 1 "$DATE" "tmd $VERSION" "User Commands"
.SH NAME
tmd \\- dump the metadata out of a tar archive
.SH SYNOPSIS
.B tmd
.BI \\-f " FILE"
.RI [ OPTION ]...
.br
.B tmd
.RB [ \\-h | \\-\\-help ]
.br
.B tmd
.RB [ \\-V | \\-\\-version ]
.SH DESCRIPTION
.B tmd
reads a tar archive and reports what is inside it without extracting anything.
By default it prints one
.BR ls (1)\\-style
line per member: the permission bits, the owner and group, the size, the
modification time the archive recorded, and the path.
.PP
The archive is opened for reading and nothing else. No member is written to
disk, no data is decoded, and the file is never modified.
.PP
Three families of tar archive are understood:
.TP
.B BSD
\\fBustar\\fR (POSIX.1\\-1988) and \\fBpax\\fR (POSIX.1\\-2001) archives, as
.BR bsdtar (1)
and libarchive write them, including pax extended headers for long paths,
high\\-numbered user IDs, and sub\\-second timestamps.
.TP
.B GNU
.BR tar (1)
archives, including the
.B L
and
.B K
blocks that carry long names and link targets, the old sparse\\-file format with
its in\\-header map and continuation blocks, and the GNU.sparse.* pax formats
0.0, 0.1 and 1.0.
.TP
.B v7
Pre\\-POSIX archives with no magic, no user names and no path prefix, as the
original Seventh Edition
.BR tar (1)
wrote them.
.PP
The format is worked out per member rather than per archive, because a real
archive mixes them: a pax archive is plain ustar headers with an occasional
extended header in front of the member that needed one. The summary reports the
most expressive dialect present, because that is the one a reader has to
understand to get every member right.
HEADER

  # ---- OPTIONS, from the program's own help --------------------------------
  echo ".SH OPTIONS"
  "$BINARY" --help \
    | sed -n '/^Options:/,/^$/p' \
    | sed '1d;/^$/d' \
    | while IFS= read -r line; do
        # "  -f, --file=FILE        read this archive; ..."
        flags="$(printf '%s' "$line" | sed -E 's/^  (.{1,24}) .*/\1/' | sed 's/ *$//')"
        text="$(printf '%s' "$line" | cut -c28-)"
        printf '.TP\n.B %s\n%s\n' \
          "$(printf '%s' "$flags" | escape_roff)" \
          "$(printf '%s' "$text" | escape_roff)"
      done

  # ---- EXIT STATUS, likewise ----------------------------------------------
  echo ".SH EXIT STATUS"
  "$BINARY" --help \
    | sed -n '/^Exit status:/,/^$/p' \
    | sed '1d;/^$/d' \
    | while IFS= read -r line; do
        code="$(printf '%s' "$line" | awk '{print $1}')"
        text="$(printf '%s' "$line" | cut -c28-)"
        printf '.TP\n.B %s\n%s\n' "$code" "$(printf '%s' "$text" | escape_roff)"
      done

  # ---- EXAMPLES, likewise --------------------------------------------------
  echo ".SH EXAMPLES"
  "$BINARY" --help \
    | sed -n '/^Examples:/,/^$/p' \
    | sed '1d;/^$/d' \
    | while IFS= read -r line; do
        command="$(printf '%s' "$line" | sed -E 's/^  (.{1,38}) .*/\1/' | sed 's/ *$//')"
        text="$(printf '%s' "$line" | cut -c42-)"
        printf '.TP\n.B %s\n%s\n' \
          "$(printf '%s' "$command" | escape_roff)" \
          "$(printf '%s' "$text" | escape_roff)"
      done

  cat <<'FOOTER'
.\" NOTE: this block is a QUOTED heredoc in scripts/gen-man.sh, so a backslash
.\" here reaches the page verbatim. Roff escapes are written with ONE backslash
.\" -- \(co, \-, \e. Doubling them, as the unquoted HEADER block above
.\" correctly does, makes roff print a literal backslash: the copyright line
.\" read "Copyright \(co 2026" on an installed page.
.SH OUTPUT
.SS The default listing
One line per member, in the shape
.BR "ls -l" " and " "tar -tvf"
both use:
.PP
.RS
.nf
\-rw\-r\-\-r\-\-  bceverly/staff          1234  2026\-09\-16 14:11  src/main.c
drwxr\-xr\-x  bceverly/staff             0  2026\-09\-16 14:10  src/
lrwxrwxrwx  bceverly/staff             0  2026\-09\-16 14:11  link \-> target
crw\-rw\-\-\-\-  root/root                1,3  2026\-09\-16 14:11  dev/null
.fi
.RE
.PP
The permission bits are the ones stored in the archive, and the leading
character comes from the member's type rather than from the mode word, because
a tar header stores no type bits. The timestamp is the modification time the
archive recorded, rendered in local time unless
.B \-\-utc
is given. A device node shows its major and minor numbers where a file shows
its size, as
.BR ls (1)
does.
.PP
Nothing else is printed to standard output: no banner and no summary unless one
is asked for, so the listing can be piped into
.BR awk (1)
without anything to strip. Warnings about damaged headers go to standard error,
which is also why
.B \-o
redirects only the report. The file it creates is mode 0644, further masked by
the umask \- so a stricter umask is honored, and a permissive one cannot leave
an integrity report that anybody can rewrite.
.SS Long form
.B \-l
prints every field of every member instead \- format, typeflag, both owner
names and numbers, the size in the archive as well as the extracted size, the
byte offset of the header, the checksum, any pax attributes that applied, and
the sparse map when there is one.
.B \-R
adds the raw 512\-byte header fields exactly as they are spelled on disk, which
is how to tell a mode field of "0000644" from one of "644    ".
.SS JSON and CSV
.B \-\-format=json
writes one object per archive with an
.B entries
array and a
.B summary
object;
.B \-\-format=csv
writes a header row and one row per member. Both are written as the archive is
read rather than built up in memory, so an archive with a million members costs
no more than one with ten.
.PP
A path in a tar archive is a string of bytes with no declared encoding. In JSON,
paths that are valid UTF\-8 are emitted as themselves; anything else is escaped
byte by byte as \eu00XX, which round\-trips through any parser and does not
destroy the value the way replacing it with U+FFFD would.
.SH WHAT IS CHECKED
.B \-c
turns the reporting into a verdict. It exits 3 when a header's checksum does not
match the bytes of its block, when the two\-block end\-of\-archive marker is
missing, or when there is non\-zero data after it. Both the signed and the
unsigned checksum convention are accepted, because tar's own history is
ambiguous about whether the header bytes were signed and rejecting one of them
means calling a perfectly good archive corrupt.
.PP
Damage that is not fatal is reported as a warning on standard error and the read
continues: a single bad header does not stop the members after it from being
listed.
.SH LIMITATIONS
.B tmd
reads plain, uncompressed tar archives. A compressed archive is recognized and
named \- gzip, bzip2, xz, zstd, lz4 and lzip \- along with the command that
produces a tar stream from it, which can then be piped in with
.BR "tmd -f -" .
.PP
Only the headers are read. Member data is stepped over, by seeking where the
input can seek, so the cost of reading an archive is proportional to the number
of members rather than to its size.
.SH SEE ALSO
.BR tar (1),
.BR bsdtar (1),
.BR pax (1),
.BR ls (1)
.SH STANDARDS
The ustar and pax interchange formats are defined by IEEE Std 1003.1 (POSIX.1),
in the specification of
.BR pax (1).
The GNU extensions are documented in the GNU tar manual, under "Controlling the
Archive Format".
.SH AUTHOR
Written by Bryan C. Everly.
.SH COPYRIGHT
Copyright \(co 2026 Bryan C. Everly.
.br
Licensed under the BSD 2\-Clause License. There is NO WARRANTY, to the extent
permitted by law.
.SH BUGS
Report bugs at https://github.com/bceverly/tmd
FOOTER
} > "$TMP"

if [ "$CHECK" -eq 1 ]; then
  if [ ! -f "$OUTPUT" ]; then
    echo "gen-man.sh: $OUTPUT does not exist — run 'make man'" >&2
    exit 1
  fi
  if ! diff -u "$OUTPUT" "$TMP" > /dev/null; then
    echo "gen-man.sh: $OUTPUT is out of date — run 'make man' and commit it" >&2
    diff -u "$OUTPUT" "$TMP" | head -40 >&2
    exit 1
  fi
  echo "  manpage is up to date"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT")"
# Only write when the content actually differs. `make build` depends on the
# manpage, so this runs whenever any source file changes -- and rewriting an
# identical file every time would leave a modified timestamp on a file with no
# diff, which is noise in `git status` and makes `make` do it again next time.
if [ -f "$OUTPUT" ] && cmp -s "$TMP" "$OUTPUT"; then
  touch "$OUTPUT"
  echo "  $OUTPUT is current"
  exit 0
fi
cp "$TMP" "$OUTPUT"
echo "  wrote $OUTPUT"
